# Generated by Django 3.0.2 on 2020-01-14 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pothole_detection_app', '0002_auto_20200114_0401'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='image_post',
        ),
    ]
